# openapi2-functions.yaml
swagger: '2.0'
info:
  title: learning-words-trial
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
host: ${managed_service}
x-google-endpoints:
- name: ${managed_service}
  allowCors: true
paths:
  # Public API
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: ${function_test_service}
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  # Secured API
  /hello2:
    get:
      summary: Greet a user 2
      operationId: hello2
      x-google-backend:
        address: ${function_test_service_2}
      responses:
        '200':
          description: A successful response
          schema:
            type: string
      x-security:
      - google_id_token:
          audiences:
          # Your OAuth2 client's Client ID must be added here. You can add
          # multiple client IDs to accept tokens from multiple clients.
          - "736194043976-jco02kmcrjb1bu748m34b9rcphf0ghdj.apps.googleusercontent.com"
          - "736194043976-ks3e2r68img0ldda4danrbo9j9olvjf3.apps.googleusercontent.com"
  # any other route is mapped to static file in a bucket
  /**:
    get:
      summary: Get a file from a GCP bucket
      operationId: getFile
      parameters:
        - name: path
          in: path
          required: true
          description: The path of the file
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
      x-google-backend:
        address: https://storage.googleapis.com/vovanoktk-static
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
        protocol: HTTP/1.1
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
