# openapi2-functions.yaml
swagger: '2.0'
info:
  title: learning-words-trial
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
host: ${managed_service}
x-google-endpoints:
- name: ${managed_service}
  allowCors: true
responses:
  SuccessfulResponse:
    description: A successful response
    schema:
      type: object
parameters:
  IdParameter:
    name: id
    in: path
    description: The ID of the entity
    required: true
    type: string
paths:
  # Words API
  /service-dictionary:
    get:
      summary: GET all words from dictionary
      operationId: getWords
      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
      x-google-backend:
        address: ${function_service_dictionary}
      security:
        - google_id_token: []
    post:
      summary: Save new word to dictionary
      operationId: addWord
      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
      x-google-backend:
        address: ${function_service_dictionary}
      security:
        - google_id_token: []
  /service-dictionary/{id}:
    get:
      summary: GET word by id
      operationId: getWord
      parameters:
        - $ref: '#/parameters/IdParameter'
      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
      x-google-backend:
        address: ${function_service_dictionary}
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - google_id_token: []
    put:
      summary: Update word by id
      operationId: putWord
      parameters:
        - $ref: '#/parameters/IdParameter'
      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
      x-google-backend:
        address: ${function_service_dictionary}
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - google_id_token: []
    delete:
      summary: DELETE word by id
      operationId: deleteWord
      parameters:
        - $ref: '#/parameters/IdParameter'
      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
      x-google-backend:
        address: ${function_service_dictionary}
        path_translation: APPEND_PATH_TO_ADDRESS
      security:
        - google_id_token: []
  # Translation API
  /service-translation:
    get:
      summary: function_service_translation
      operationId: mainTranslation
      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
      x-google-backend:
        address: ${function_service_translation}
      security:
        - google_id_token: []
  /service-translation/translate:
    post:
      summary: function_service_translation
      operationId: translate
      responses:
        '200':
          $ref: '#/responses/SuccessfulResponse'
      x-google-backend:
        address: ${function_service_translation}/translate
      security:
        - google_id_token: []
  # Configure root route to serve index.html file
  /:
    get:
      summary: Get a get Index from a GCP bucket
      operationId: getIndex
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
      x-google-backend:
        address: https://storage.googleapis.com/vovanoktk-static/index.html
        disable_auth: true
        protocol: HTTP/1.1        
  # any other route is mapped to static file in a bucket
  /**:
    get:
      summary: Get a file from a GCP bucket
      operationId: getFile
      parameters:
        - name: path
          in: path
          required: true
          description: The path of the file
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
            format: binary
      x-google-backend:
        address: https://storage.googleapis.com/vovanoktk-static
        path_translation: APPEND_PATH_TO_ADDRESS
        disable_auth: true
        protocol: HTTP/1.1
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-audiences: "${google_oauth_client_id}"
