name: publish-frontend-to-bucket

on:
  workflow_dispatch

jobs:
  upload_fe:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: ls
    - run: cp -r frontend/client-app .
    - run: ls -la
    - run: npm i 
    - run: npm run build 
    - run: npm run postbuild 
    - run: ls -la 
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/736194043976/locations/global/workloadIdentityPools/idpool/providers/idprovider'
        service_account: 'githubsanew@learning-words-trial.iam.gserviceaccount.com'
        token_format: 'access_token'
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    - name: Delete files from bucket
      run: gsutil rm gs://vovanoktk-static/**
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'build'
        destination: 'vovanoktk-static'