name: publish-backend-to-bucket

on:
  workflow_dispatch

jobs:
  upload_zip_files:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - name: Install zip
      uses: montudor/action-zip@v1
    - run: ls
    - id: 'zipservice'
      run: zip -qq -r test-service.zip *
      working-directory: backend/service-test
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/idpool/providers/idprovider'
        service_account: ${{ vars.GCP_GITHUB_SERVICE_ACCOUNT }}
        token_format: 'access_token'
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'backend/service-test/test-service.zip'
        destination: 'vovanoktk-functions'