name: publish-backend-to-bucket

on:
  push:
    branches:
    - 'main'

jobs:
  upload_zip_files:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v1
    - id: 'zip service'
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r test-service.zip backend/service-test
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/736194043976/locations/global/workloadIdentityPools/githubactions/providers/github'
        service_account: 'github-sa@learning-words-trial.iam.gserviceaccount.com'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'test-service.zip'
        destination: 'vovanoktk-functions/test-servise.zip'