name: destroy-whole-infra

on:
  workflow_dispatch:

jobs:
  execute_terraform_destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
    - run: ls
    - run: cd infra
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/idpool/providers/idprovider'
        service_account: ${{ vars.GCP_GITHUB_SERVICE_ACCOUNT }}
        token_format: 'access_token'
    - name: Terraform Init
      id: init
      run: terraform -chdir=infra init
    - run: ls -la infra
    - name: Terraform Destroy!
      id: apply
      run: terraform -chdir=infra destroy -auto-approve
