name: update-function

on:
  workflow_dispatch:
    inputs:
        service_name:
          description: 'Which module to re-deploy'
          required: true
          default: 'service-dictionary'

jobs:
  update_cloud_function:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3
    - run: ls
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/idpool/providers/idprovider'
        service_account: ${{ vars.GCP_GITHUB_SERVICE_ACCOUNT }}
        token_format: 'access_token'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: 'Use to deploy a cloud function gen 2'
      run: 'gcloud functions deploy ${{ inputs.service_name }} --gen2 --runtime=nodejs18 --region=us-central1 --source=backend/${{ inputs.service_name }} --trigger-http --allow-unauthenticated --entry-point=main --memory=256MB --timeout=60s'
