name: update-service-dictionary

on:
  workflow_dispatch:
  push:
    paths:
      - backend/service-dictionary/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - name: Deploy service
        uses: ./.github/workflows/update-cloud-function.yaml
        with:
          service_name: service-dictionary