name: update-service-dictionary

on:
  push:
    paths:
      - backend/service-dictionary/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy service
        uses: ./.github/workflows/update-cloud-function
        with:
          service_name: service-dictionary