name: update-service-dictionary

on:
  workflow_dispatch:
  push:
    paths:
      - backend/service-dictionary/**

jobs:
  deploy:
    uses: ./.github/workflows/update-cloud-function.yaml
    with:
      service_name: service-dictionary